namespace XamlConstructor.Generator;

public static class Source
{
    internal const string AttributeFullName = "XamlConstructorAttribute";

    internal const string AttributeText = $$"""
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by the {{nameof(XamlConstructor)}} source generator.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        using System;

        /// <summary>
        /// Generates an empty constructor for XAML Design Mode.
        /// All fields and properties will be assigned null!.
        /// </summary>
        /// <example>
        /// [XamlConstructor]
        /// public partial class MyViewModel
        /// {
        ///     private readonly ILogger _logger;
        ///     private readonly IService _service;
        /// }
        /// </example>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
        internal sealed class {{AttributeFullName}}() : Attribute;
        """;
}
