on:
  push:
    branches:
    - main
    tags:        
      - v*
  pull_request:

jobs:
  build:
    name: windows-latest
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # for minver
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
    - name: Execute build and run tests
      run: |
        dotnet build --configuration Release /nologo
        dotnet test --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: XamlConstructor
        path: artifacts/*
    - name: Publish NuGet package
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        foreach($file in (Get-ChildItem "artifacts/" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }
